apiVersion: apps/v1
kind: Deployment
metadata:
  name: profileservice-depl
  labels:
    app: profileservice
spec:
  selector:
    matchLabels:
      app: profileservice
  replicas: 1
  template:
    metadata:
      labels:
        app: profileservice
    spec:
      containers:
        - name: profileservice
          image: gokulcapstoneproject.azurecr.io/profileservice:latest
          env:
            - name: ConnectionStrings__keyvaulturi
              value: "https://matrimonialapp.vault.azure.net/"
            - name: RabbitMQ__Host
              value: "rabbitmq-clusterip-srv"
            - name: RabbitMQ__UserName
              value: "guest"
            - name: RabbitMQ__Password
              value: "guest"
            - name: RabbitMQ__ProfileQueueName
              value: "matrimonial-profile-queue"
            - name: RabbitMQ__PaymentQueueName
              value: "matrimonial-payment-queue"
            - name: RabbitMQ__AuthQueueName
              value: "matrimonial-auth-queue"
            - name: "Azure_Client_ID"
              value: "2256bf2f-630d-4f29-8d8b-d8eb52369b66"
          ports:
            - containerPort: 80
              name: profileservice
---
apiVersion: v1
kind: Service
metadata:
  name: profileservice-clusterip-srv
spec:
  selector:
    app: profileservice
  type: ClusterIP
  ports:
    - name: profileservice
      protocol: TCP
      port: 80
      targetPort: 80
